name: Count Python Files in Repository

on: [push]

jobs:
  count-python-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Count lines in files ending in .py
      run: |
        echo "Repository contains $(find . -name '*.py' | xargs wc -l) Python files."
