name: Count lines in Python Files in Repository

on: [push]

jobs:
  count-python-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Count lines in files ending in .py
      run: |
        find . -name '*.py' | xargs wc -l | sed -E "s/^[^0-9]*([0-9]+) (.*)$/\2: \1 lines/"
