name: Count lines in Python Files in Repository

on: 
    workflow_dispatch:

jobs:
  count-python-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Count lines in files ending in .py
      run: |
        find . -name '*.py' | xargs wc -l
